name: HSN Scraper Cron

on:
  schedule:
    # Runs at 08:00 and 15:00 UTC (which is 09:00 and 16:00 UTC+1 / local time)
    - cron: "0 8,15 * * *"
  workflow_dispatch: # Allows you to manually trigger it from the GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Scraper Endpoint
        run: |
          echo "Triggering the scrape API..."
          curl -s -m 60 "https://hsn-scraper.vercel.app/api/scrape?secret=${{ secrets.CRON_SECRET }}"
